tasks/urls.py
from django.urls import path
from .views import TasksListView, TaskUpdateView, task_status_update, \
    user_recent_activity, TasksProgressView, TasksCreateView, user_favourite_categories


app_name = 'tasks'

urlpatterns = [
    path('tasks/', TasksListView.as_view(), name='tasks'),
    path('page/<int:page>', TasksListView.as_view(), name='paginator'),
    path('task_create/', TasksCreateView.as_view(), name='task_create'),
    path('recent_stats', user_recent_activity, name='recent_stats'),
    path('fav_cats', user_favourite_categories, name='fav_cats'),
    path('task_update/<int:pk>/', TaskUpdateView.as_view(), name='task_update'),
    path('task_status_update/<int:task_id>/', task_status_update, name='task_status_update'),
    path('tasks_progress/', TasksProgressView.as_view(), name='task_progress'),
]

todo3/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from users.views import AboutView, IndexView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('home/', IndexView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('todo/users/', include('users.urls', namespace='users')),
    path('todo/tasks/', include('tasks.urls', namespace='tasks')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import UserAuthView, UserRegView, UserLogoutView, UserUpdateView, ProfileView

app_name = 'users'

urlpatterns = [
    path('auth/', UserAuthView.as_view(), name='auth'),
    path('reg/', UserRegView.as_view(), name='reg'),
    path('user_update/<int:pk>', UserUpdateView.as_view(), name='user_update'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
]

tasks/models.py
from django.db import models
from users.models import User
from django.utils import timezone


class TaskCategory(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return f'Категория {self.name}'


class Task(models.Model):
    title = models.CharField(max_length=1024)
    description = models.TextField()
    creation_dateTime = models.DateTimeField(default=timezone.localtime(timezone.now()))
    finished_dateTime = models.DateTimeField(null=True, blank=True)
    deadline_dateTime = models.DateTimeField()
    image = models.ImageField(upload_to='tasks_images', null=True,
                              blank=True)
    category = models.ForeignKey(to=TaskCategory, on_delete=models.CASCADE)
    is_finished = models.BooleanField(default=False)
    owner = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Задача {self.title} категории {self.category.name} от {self.creation_dateTime}'

tasks/forms.py
from .models import Task
from django.forms import ModelForm
from django import forms
from .models import TaskCategory
from users.models import User


class TaskUpdateForm(ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control'
    }))
    deadline_dateTime = forms.DateTimeField(widget=forms.DateTimeInput(attrs={
        'class': 'form-control',
    }))
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'custom-file-input'
    }), required=False)
    category = forms.ModelChoiceField(queryset=TaskCategory.objects.all(), empty_label=None)

    class Meta:
        model = Task
        fields = ('description', 'deadline_dateTime', 'category', 'image')


class TaskCreateForm(ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={
        'class': "form-control", 'placeholder': 'Заголовок задачи'
    }))
    description = forms.CharField(widget=forms.TextInput(attrs={
        'class': "form-control", 'placeholder': 'Описание задачи'
    }))
    deadline_dateTime = forms.DateTimeField(widget=forms.DateTimeInput(attrs={
        'type': 'datetime-local',
        'class': 'form-control'
    }))
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'custom-file-input'
    }), required=False)
    category = forms.ModelChoiceField(queryset=TaskCategory.objects.all(), widget=forms.Select, empty_label=None)
    owner = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput, required=False)

    class Meta:
        model = Task
        fields = ('title', 'description', 'deadline_dateTime', 'image', 'category', 'owner')

tasks/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.utils import timezone
from django.views.generic import CreateView, ListView, TemplateView, UpdateView

from common.views import TitleMixin

from .forms import TaskCreateForm, TaskUpdateForm
from .models import Task
from .tasks_services import (get_in_process_tasks, get_last_finished_tasks,
                             get_most_favourite_categories,
                             get_recent_tasks_stats, get_task)


class TasksListView(TitleMixin, ListView):
    model = Task
    template_name = 'tasks.html'
    paginate_by = 4
    title = 'To Do - Задачи'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TasksListView, self).get_context_data()
        context['tasks_edit_forms'] = [TaskUpdateForm(
            instance=task) for task in self.get_queryset()]
        context['create_task_form'] = TaskCreateForm()
        return context

    def get_queryset(self):
        return get_in_process_tasks(owner=self.request.user)


class TaskUpdateView(UpdateView):
    model = Task
    form_class = TaskUpdateForm

    def get_success_url(self):
        return reverse('tasks:tasks')


@login_required
def task_status_update(request, task_id):
    """Сервис, устанавливающий статус таска в законченный"""
    if request.method == 'POST':
        task = get_task(task_id)
        task.is_finished = True
        task.finished_dateTime = timezone.localtime(timezone.now())
        task.save()
        return HttpResponseRedirect(reverse('tasks:tasks'))
    elif request.method == 'GET':
        return HttpResponseRedirect(reverse('tasks:tasks'))


class TasksProgressView(TemplateView):
    template_name = 'progress.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'{self.request.user.username} - Статистика'
        context['recent_tasks'] = get_last_finished_tasks(
            owner=self.request.user)
        return context


class TasksCreateView(CreateView):
    model = Task
    form_class = TaskCreateForm

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('tasks:tasks')


@login_required
def user_recent_activity(request):
    """Сервис, возвращающий данные о недавней активности пользователя
     (последние 6 месяцев)
    """
    return JsonResponse(get_recent_tasks_stats(request.user), safe=False)


@login_required
def user_favourite_categories(request):
    """Сервис, возвращающий данные о самых востребованных категориях пользователя"""
    return JsonResponse(get_most_favourite_categories(request.user), safe=False)

templates/account_settings.html
{% extends 'base-head.html' %}
{% load static %}

{% block content %}
    <form class="row g-3 mt-5 mb-5" style="background: white;" method="post" action="{% url 'users:user_update' form.instance.pk %}" enctype="multipart/form-data">
        {% csrf_token %}
        <h3 class="text-center">Профиль</h3>
        <div class="col-md-3 d-flex justify-content-center align-items-center">
            <label for="{{ form.image.id_for_label }}">
                <img width="100" height="100"
                     src="{% if form.instance.image %}{{ form.instance.image.url }}{% else %}{% static 'vendor/images/user.png' %}{% endif %}"
                     alt="" style="border-radius: 100px;cursor: pointer;">
            </label>
            {{ form.image }}
        </div>
        <input type="file" id="imageInput" accept="image/*" style="display: none;" />
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <label for="{{ form.first_name.id_for_label }}" class="form-label">Имя</label>
                    {{ form.first_name }}
                </div>
                <div class="col-md-6 col-sm-12">
                    <label for="{{ form.last_name.id_for_label }}" class="form-label">Фамилия</label>
                    {{ form.last_name }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <label for="{{ form.email.id_for_label }}" class="form-label">Почта</label>
                    {{ form.email }}
                </div>
                <div class="col-md-6 col-sm-12">
                    <label for="{{ form.username.id_for_label }}" class="form-label">Имя пользователя</label>
                    {{ form.username }}
                </div>
            </div>
        </div>
        <div class="col-lg-12 mt-5 d-flex justify-content-center align-items-center">
            <img width="36" height="36" class="img-fluid mx-1" src="{% static 'vendor/images/oauth/google.png' %}" alt="google">
            <input type="text" disabled value="batyamax17@gmail.com" style="width: 30%;">
        </div>
        <div class="col-lg-12 mt-5 d-flex justify-content-center align-items-center">
            <img width="36" height="36" class="img-fluid mx-1" src="{% static 'vendor/images/oauth/facebook.png' %}" alt="facebook">
            <input type="text" disabled value="https://www.facebook.com/maxahmed1234." style="width: 30%;">
        </div>
        <div class="col-lg-12 mt-5 d-flex justify-content-center align-items-center">
            <img width="36" height="36" class="img-fluid mx-1" src="{% static 'vendor/images/oauth/github-sign.png' %}" alt="github">
            <input type="text" disabled value="https://github.com/zormnus1241144114441" style="width: 30%;">
        </div>
        <div class="col-12 mb-5 mt-5 d-flex justify-content-center align-items-center">
            <button type="submit" class="btn btn-primary" id="profile-edit-save-btn">Сохранить изменения</button>
        </div>
    </form>
{% endblock %}

templates/base-head.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'vendor/images/website-icon.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'vendor/css/styles.css' %}">
    <title>{{ title }}</title>
    {% block styles %}
    {% endblock %}
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}"><img class="icon" src="{% static 'vendor/images/logo.svg' %}" alt=""></a>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                        <li class="nav-item mx-5">
                            <a class="nav-link active" style="font-weight: bold;" aria-current="page" href="{% url 'home' %}">Главная</a>
                        </li>
                        <li class="nav-item mx-5">
                            <a class="nav-link" href="{% url 'about' %}">О сервисе</a>
                        </li>
                        {% if not user.is_authenticated %}
                            <li class="nav-item mx-5">
                                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalAuth">
                                    Войти
                                </button>
                            </li>
                            <li class="nav-item mx-5">
                                <button type="button" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#modalReg">
                                    Зерегистрироваться
                                </button>
                            </li>
                        {% endif %}
                        <li class="nav-item dropdown mx-5">
                            {% if user.is_authenticated %}
                            <div class="d-flex">
                                <img class="img-fluid user-mini-img d-none d-lg-block"
                                     src="{% if user.image %}{{ user.image.url }}{% else %}{% static 'vendor/images/user.png' %}{% endif %}"
                                     alt="avatar">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ user.username }}
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="{% url 'tasks:tasks' %}"><i class="fa-solid fa-calendar-days"></i> Задачи</a></li>
                                    <li><a class="dropdown-item" href="{% url 'users:profile' %}"><i class="fa-solid fa-gears"></i> Настройки профиля</a></li>
                                    <li><a class="dropdown-item" href="{% url 'tasks:task_progress' %}"><i class="fa-solid fa-bars-progress"></i> Прогресс</a></li>

                                    {% if user.is_superuser or user.is_stuff %}
                                        <li><a class="dropdown-item" href="#"><i class="fa-solid fa-lock"></i> Админ-панель</a></li>
                                    {% endif %}
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'users:logout' %}"><i class="fa-solid fa-right-from-bracket"></i> Выйти</a></li>
                                </ul>
                            </div>
                            {% endif %}
                        </li>
                    </ul>
                </div>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>



        <!--        Всплывающее окно авторизации-->
        <div class="modal fade" id="modalAuth" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modelAuthLabel">Авторизация</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form id="auth-form" method="post" action="{% url 'users:auth' %}">
                            {% csrf_token %}
                            <input type="hidden" name="login_form" value="1">
                            <div class="mb-3">
                                <label for="{{ auth_form.username.id_for_label }}" class="form-label">Имя пользователя</label>
                                {{ auth_form.username }}
                            </div>
                            <div class="mb-3">
                                <label for="{{ auth_form.password.id_for_label }}" class="form-label">Пароль</label>
                                {{ auth_form.password }}
                                <div class="mt-2">
                                    <a href="#">Забыли пароль?</a>
                                </div>
                            </div>
                            <div class="mb-3 d-flex justify-content-center">
                                <button type="submit" class="btn btn-primary">Войти</button>
                            </div>
                        </form>
                        <div class="d-flex justify-content-center">
                            <p>Или используйте сторонние сервисы</p>
                        </div>
                        <div class="oauth__refs d-flex justify-content-center">
                            <div class="google__ref mx-3">
                                <a href="#"><img class="img-fluid" src="{% static 'vendor/images/oauth/google.png' %}" alt="google-auth-link"></a>
                            </div>
                            <div class="facebook__ref mx-3">
                                <a href="#"><img class="img-fluid" src="{% static 'vendor/images/oauth/facebook.png' %}" alt="facebook-auth-link"></a>
                            </div>
                            <div class="github__ref mx-3">
                                <a href="#"><img class="img-fluid" src="{% static 'vendor/images/oauth/github-sign.png' %}" alt="facebook-auth-link"></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


<!--        Всплывающее окно регистрации-->
        <div class="modal fade" id="modalReg" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modalRegLabel">Регистрация</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="{% url 'users:reg' %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="d-flex">
                                <div class="mb-3">
                                    <label for="{{ reg_form.first_name.id_for_label }}" class="form-label">Имя</label>
                                    {{ reg_form.first_name }}
                                </div>
                                <div class="mb-3">
                                    <label for="{{ reg_form.last_name.id_for_label }}" class="form-label">Фамилия</label>
                                    {{ reg_form.last_name }}
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="{{ reg_form.username.id_for_label }}" class="form-label">Имя пользователя</label>
                                {{ reg_form.username }}
                            </div>
                            <div class="mb-3">
                                <label for="{{ reg_form.email.id_for_label }}" class="form-label">Почта</label>
                                {{ reg_form.email }}
                            </div>
                            <div class="mb-3">
                                <label for="{{ reg_form.password1.id_for_label }}" class="form-label">Пароль</label>
                                {{ reg_form.password1 }}
                            </div>
                            <div class="mb-3">
                                <label for="{{ reg_form.password2.id_for_label }}" class="form-label">Введите пароль ещё раз</label>
                                {{ reg_form.password2 }}
                            </div>
                            <div class="mb-3 d-flex justify-content-center">
                                <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                            </div>
                        </form>
                        <div class="d-flex justify-content-center">
                            <p>Или используйте сторонние сервисы</p>
                        </div>
                        <div class="oauth__refs d-flex justify-content-center">
                            <div class="google__ref mx-3">
                                <a href=""><img class="img-fluid" src="{% static 'vendor/images/oauth/google.png' %}" alt="google-auth-link"></a>
                            </div>
                            <div class="facebook__ref mx-3">
                                <a href=""><img class="img-fluid" src="{% static 'vendor/images/oauth/facebook.png' %}" alt="facebook-auth-link"></a>
                            </div>
                            <div class="github__ref mx-3">
                                <a href=""><img class="img-fluid" src="{% static 'vendor/images/oauth/github-sign.png' %}" alt="facebook-auth-link"></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% block content %}
    {% endblock %}

    {% block scripts %}
    {% endblock %}
    </div>


    <script src="https://kit.fontawesome.com/01526c112b.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

templates/tasks.html
{% extends 'base-head.html' %}
{% load static %}

{% block styles %}
    <style>
        .fade-out {
            animation: fadeOut ease 1s;
        }

        @keyframes fadeOut {
            0% {
                opacity: 1;
            }
            100% {
                opacity: 0;
            }
        }
	</style>
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row d-flex justify-content-center mt-5">
            <div class="col-lg-2">
                <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createTaskModal">
                    Создать задачу
                </button>
            </div>
        </div>

        <div class="row mt-5">
            {% if object_list %}
                {% for task in object_list %}
                    <div class="col-xl-6 col-lg-3 d-flex mt-5">
                        <div class="card flex-fill position-relative" id='task{{ task.pk }}'>
                            <img class="img-fluid" src="{% if task.image %}{{ task.image.url }}{% endif %}" alt="">
                            <div class="card-body">
                                <h5 class="card-title">{{ task.title }} ({{ task.category.name }})</h5>
                                <p class="card-text">{{ task.description }}</p>
                                <p class="card-text">Дата создания {{ task.creation_dateTime }}</p>
                                <p class="card-text">Дедлайн {{ task.deadline_dateTime }}</p>
                                <a id="taskDoneBtn{{ task.pk }}" onclick="taskRemoveAnimation({{ task.pk }})" class="btn btn-primary">Отметить как сделанное</a>
                            </div>
                            <div class="position-absolute top-0 start-100 translate-middle">
                                <button class="btn btn-primary btn-sm"
                                        style="width: 30px; height: 30px; border-radius: 15px; padding: 0;
                                        position: relative;" data-bs-toggle="modal" data-bs-target="#task{{ task.pk }}EditModal">
                                    <img class="icon" src="{% static 'vendor/images/pen-to-square-solid.svg' %}" alt="edit_icon" style="width: 20px; height: 20px; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">
                                </button>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="col-lg-12 col-mb-5 mt-5 justify-content-center text-center">
                    <h4>Тут пока что ничего нет</h4>
                    <img class="img-fluid mb-5" src="{% static 'vendor/images/out-0.png' %}" alt="" width="50%" style="border-radius: 50px;">
                </div>
            {% endif %}
        </div>

        {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center mt-5">
                    <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                        <a class="page-link"
                           href="{% if page_obj.has_previous %} {% url 'tasks:paginator' page_obj.previous_page_number %} {% else %} # {% endif %}"
                           tabindex="-1" aria-disabled="true">
                            Предыдущая
                        </a>
                    </li>
                    {% for page in paginator.page_range %}
                        <li class="page-item">
                            <a class="page-link" href="{% url 'tasks:paginator' page %}">
                                {{ page }}
                            </a>
                        </li>
                    {% endfor %}
                    <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                        <a class="page-link"
                           href="{% if page_obj.has_next %} {% url 'tasks:paginator' page_obj.next_page_number %} {% else %} # {% endif %}">
                            Следующая
                        </a>
                    </li>
                </ul>
            </nav>
        {% endif %}

        {% for form in tasks_edit_forms %}
            <div class="modal fade" id="task{{ form.instance.pk }}EditModal" tabindex="-1" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="modelAuthLabel">Изменение задачи</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form action="{% url 'tasks:task_update' form.instance.pk %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <img class="img-fluid" src="{% if form.instance.image %}{{ form.instance.image.url }}{% endif %}" alt="">
                                    <label for="{{ form.image.id_for_label }}" class="form-label">Изображение задания</label>
                                    {{ form.image }}
                                </div>
                                <div class="mb-3">
                                    <label for="{{ form.description.id_for_label }}" class="form-label">Описание задачи</label>
                                    {{ form.description }}
                                </div>
                                <div class="mb-3">
                                    <label for="task_deadline" class="form-label">Дедлайн задачи</label>
                                    {{ form.deadline_dateTime }}
                                </div>
                                <div class="mb-3">
                                    <label for="{{ form.category.id_for_label }}" class="form-label">Категория задачи</label>
                                    {{ form.category }}
                                </div>
                                <div class="mb-3 d-flex justify-content-center">
                                    <button type="submit" class="btn btn-primary">Сохранить изменения</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

        <div class="modal fade" id="createTaskModal" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modelAuthLabel">Новая задача</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form action="{% url 'tasks:task_create' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="{{ create_task_form.title.id_for_label }}" class="form-label">Заголовок задания</label>
                                {{ create_task_form.title }}
                            </div>
                            <div class="mb-3">
                                <label for="{{ create_task_form.image.id_for_label }}" class="form-label">Изображение задания</label>
                                {{ create_task_form.image }}
                            </div>
                            <div class="mb-3">
                                <label for="{{ create_task_form.description.id_for_label }}" class="form-label">Описание задачи</label>
                                {{ create_task_form.description }}
                            </div>
                            <div class="mb-3">
                                <label for="{{ create_task_form.deadline_dateTime.id_for_label }}" class="form-label">Дедлайн задачи</label>
                                {{ create_task_form.deadline_dateTime }}
                            </div>
                            <div class="mb-3">
                                <label for="{{ create_task_form.category.id_for_label }}" class="form-label">Категория задачи</label>
                                {{ create_task_form.category }}
                            </div>
                            <div class="mb-3 d-flex justify-content-center">
                                <button type="submit" class="btn btn-primary">Создать</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block scripts %}
    <script src="{% static 'vendor/js/anims.js' %}"></script>
{#    <script src="{% static 'vendor/js/wow.min.js' %}"></script>#}
{#    <script>#}
{#        new WOW().init();#}
{#    </script>#}
{% endblock %}